import React from 'react'
import { useState ,useEffect } from 'react'
import Formfield from '../components/Formfield'
import Card from '../components/Card'
import Loader from '../components/Loader'

const Home = () => {

    const [loading , setLoading] = useState(false);
    const [allPosts , setAllPosts] = useState(null);
    const [searchText , setSearchText] = useState('abc');

  return (
    <section>
        <div>
            <h2 className='font-extrabold text-[32px]'>The community Showcase</h2>
            <p>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
        </div>

        <div className='mt-16'>
            <Formfield/>
        </div>

        <div className='mt-10'>
            {loading ? (
                <div className='flec justify-center items-center'>
                    <Loader/>
                </div>
            ) : (
                <>
                    {searchText && (
                        <h2>Showing results for <span>{searchText}</span></h2>
                    )}
                    <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>

                    </div>
                </>
            )}
        </div>

    </section>
  )
}

export default Home